package me.smalltownships;

import java.io.File;
import java.sql.*;
import java.util.Properties;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

public class MySQLHandler implements AutoCloseable {
	
	private static final Properties props = new Properties(System.getProperties());
	private static final String WEBAPPS_PATH = System.getProperty("catalina.home") + File.separator + "webapps" + File.separator;
	private static final String XML_PATH = WEBAPPS_PATH + "SmallTownShipsConfig.xml";
	private static final String SSL_PATH = WEBAPPS_PATH + "SSL" + File.separator;
	private static final String TRUST_PATH = SSL_PATH + "truststore";
	private static final String KEY_PATH = SSL_PATH + "keystore";
	
	static {
		// set default connection properties
		props.setProperty("allowPublicKeyRetrieval", "true");
		props.setProperty("serverTimezone", "UTC");
		// Load JDBC connection settings from XML file
		try {
			DocumentBuilder builder = DocumentBuilderFactory.newInstance().newDocumentBuilder();
			Document doc = builder.parse(new File(XML_PATH));
			if (doc == null) {
				throw new RuntimeException("Could not parse XML file " + XML_PATH);
			}
			Element root = doc.getDocumentElement();
			if (root == null) {
				throw new RuntimeException("Could not extract document root");
			}
			root.normalize();
			// extract truststore and keystore passwords
			Element db = (Element) root.getElementsByTagName("database").item(0);
			if (db == null) {
				throw new RuntimeException("Could not extract database settings from XML file");
			}
			String ssl = db.getElementsByTagName("sslMode").item(0).getTextContent();
			if (ssl == null) {
				throw new RuntimeException("Could not find \"sslMode\" tag in \"database\" node of XML file");
			}
			props.setProperty("sslMode", ssl);
			// if SSL is disabled, don't load SSL settings
			if (!ssl.equals("DISABLED")) {
				String ts = db.getElementsByTagName("truststore").item(0).getTextContent();
				if (ts == null) {
					throw new RuntimeException("Could not find \"truststore\" tag in \"database\" node of XML file");
				}
				String ks = db.getElementsByTagName("keystore").item(0).getTextContent();
				if (ks == null) {
					throw new RuntimeException("Could not find \"keystore\" tag in \"database\" node of XML file");
				}
				props.setProperty("trustCertificateKeyStoreUrl", "file:" + TRUST_PATH);
				props.setProperty("clientCertificateKeyStoreUrl", "file:" + KEY_PATH);
				props.setProperty("trustCertificateKeyStorePassword", ts);
				props.setProperty("clientCertificateKeyStorePassword", ks);
				props.setProperty("trustCertificateKeyStoreType", "JKS");
				props.setProperty("clientCertificateKeyStoreType", "JKS");
			}
		} catch (Exception e) {
			throw new RuntimeException("Exception in initializing MySQLHandler class", e);
		}
	}
	
	Connection con;
	
	public MySQLHandler() {
		try {
			DocumentBuilder builder = DocumentBuilderFactory.newInstance().newDocumentBuilder();
			Document config = builder.parse(new File(XML_PATH));
			if (config == null) {
				throw new RuntimeException("Could not parse XML file " + XML_PATH);
			}
			Element root = config.getDocumentElement();
			if (root == null) {
				throw new RuntimeException("Could not extract document root");
			}
			root.normalize();
			Element db = (Element) root.getElementsByTagName("database").item(0);
			if (db == null) {
				throw new RuntimeException("Could not extract database settings from XML file");
			}
			String dbpswd = db.getElementsByTagName("password").item(0).getTextContent();
			if (dbpswd == null) {
				throw new RuntimeException("Could not find \"password\" tag in \"database\" node of XML file");
			}
			
			Properties p = new Properties(props);
			p.setProperty("user", "root");
			p.setProperty("password", dbpswd);

			Class.forName("com.mysql.cj.jdbc.Driver");
			con = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/smalltownships", p);
			if(con == null) {
				throw new RuntimeException("Not connected to database");
			}
		} catch (Exception e) {
			throw new RuntimeException("Exception in constructing MySQLHandler object", e);
		}

	}

	/**
	 * Designed to be called by LoginHandler / Registration page
	 *  Returns a result set that can be manipulated
	 * @deprecated - Stored procedures should be used instead
	 *  
	 *  
	 *  @param SQL string to be executed
	 *  @return Result set of table that was queried
	 */
	public ResultSet queryTable(String sql) {
		try {
			Statement stmt = con.createStatement();
			return stmt.executeQuery(sql);
		} catch (SQLException e) {
			throw new RuntimeException("Exception executing query " + sql, e);
		}
	}
	/**
	 * Used to access stored procedures from database
	 * 
	 * @param procedureName String
	 * @return ResultSet generated by stored procedure
	 */
	public ResultSet callProcedure(String procedureName) {
		String sql = "{CALL "+procedureName+"}";
		try {
			CallableStatement stmt = con.prepareCall(sql);
			return stmt.executeQuery();
		} catch (SQLException e) {
			throw new RuntimeException("Exception calling procedure " + procedureName, e);
		}
	}
	/**
	 * Used to call stored procedures that require arguments in a safe way
	 * 
	 * @param procedureName String with '?' filled in as arguments
	 * @param arg - int - number of arguments
	 * @param args - String[] - contains arguments to be passed in
	 * @return ResultSet generated by stored procedure
	 */
	public ResultSet callProcedure(String procedureName, int arg, String[] args) {
		String sql = "{ CALL "+procedureName+" }";
		//System.out.println(sql);
		try {
			CallableStatement stmt = con.prepareCall(sql);
			for (int i = 1; i <= arg; i++) {
				stmt.setString(i, args[i-1]);
			}
			return stmt.executeQuery();
		} catch (SQLException e) {
			throw new RuntimeException("Exception calling procedure " + procedureName, e);
		}
	}

	/**
	 * Used to call stored procedures that require arguments in a safe way
	 * 
	 * @param procedureName String with '?' filled in as arguments
	 * @param args - Object[] - contains arguments to be passed in
	 * @return ResultSet generated by stored procedure
	 */
	public ResultSet callProcedure(String procedureName, Object ...args) {
		String sql = "{ CALL "+procedureName+" }";
		//System.out.println(sql);
		try {
			CallableStatement stmt = con.prepareCall(sql);
			for (int i = 1; i <= args.length; i++) {
				stmt.setObject(i, args[i-1]);
			}
			return stmt.executeQuery();
		} catch (SQLException e) {
			throw new RuntimeException("Exception calling procedure " + procedureName, e);
		}
	}

	/**
	 * 	Function for issuing data manipulation statements to database
	 * @deprecated - called procedures should be used instead
	 *  @param sql - String SQL statement that should return nothing
	 *  @return True if statement executed, false if an exception was thrown
	 */
	public boolean updateTable(String sql) {
		try {
			Statement stmt = con.createStatement();
			stmt.executeUpdate(sql);
			return true;
		} catch (SQLException e) {
			throw new RuntimeException("Exception executing query " + sql, e);
		}
	}
	
	/**
	 * Utility method, allowing for conversion of verifiedAccounts table to String
	 * 
	 * @param ResultSet from the verifiedAccounts table to be converted to string
	 * @return String representation of table
	 */
	public String verifiedToString(ResultSet rs) {
		String s = "";
		try {
			int columnCount = rs.getMetaData().getColumnCount();
			while(rs.next()){
				s += rs.getRow() + ": ";
				for (int i = 1; i <= columnCount; i++) {
					String value = rs.getString(i);
					s += "[" + value + "] ";
				}
				s += System.lineSeparator();
			}
			return s;
		} catch (SQLException e) {
			throw new RuntimeException("SQL Exception converting verifiedaccounts rows to strings", e);
		}
	}

	@Override
	public void close() {
		// Close the database connection
		// https://stackoverflow.com/a/249149
		if (con != null) {
			try {
				con.close();
			} catch (SQLException e) {
				throw new RuntimeException("Exception closing database connection", e);
			}			
		}
	}
}
